apiVersion: v1
kind: Namespace
metadata:
  name: home-agent
  labels:
    purpose: "HomeAutomation"  # Optional label for organization or categorization
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: home-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi  # Adjust the storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: home-agent
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest  # Replace with the appropriate Ollama image
        ports:
        - containerPort: 11434         # Replace with the actual port if different
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "7Gi"
        #     cpu: "3"
        lifecycle:
         postStart:
           exec:
             command: ["/bin/bash", "-c", "ollama run llama3.2"]
        volumeMounts:
        - mountPath: /root/.ollama     # Mount the PVC to this path
          name: ollama-volume
      volumes:
      - name: ollama-volume
        persistentVolumeClaim:
          claimName: ollama-pvc  # Reference the PVC created above
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: home-agent
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${ASSIGNED_IP}
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: LoadBalancer  # Change to LoadBalancer if you want an external IP
